### ISSUE TITLE
Installation from master branch

### ISSUE THREAD

**Issue by diegojromerolopez** [caktus/django-sticky-uploads#22]
Hello Caktus team.

I'm trying to install your master branch in one of my projects doing:

```sh
pip install git+git://github.com/caktus/django-sticky-uploads@master
```

But the Javascript bundle files are not automatically generated.

I'm doing this because versión 0.4.0 is not compatible with Django 1.10 and for other reasons I have to use Django 1.10.

Do I have to execute the makefile you include in this repo? Is there any other way of creating this bundle js files? Maybe setup.py script could create this files?

Any help is really appreciated.

Thank you very much.

**Comment by mlavin** [comment]
You don't *need* the bundled/minified files to run the project if you include the non-minified version in the HTML instead

```
<script src="{% static 'stickyuploads/js/django-uploader.js' %}"></script>
```

`setup.py` cannot run these scripts since we can't assume that the system installing the package with have the necessary Node modules (`uglify`) to run them.

**Comment by diegojromerolopez** [comment]
But the widget StickyUploadWidget is loading the bundled js via Media.js, so I'd have to extends that class and rewrite Media.js.

I think other solution would be adding the bundled JS to the repository. Is that possible?

**Comment by mlavin** [comment]
Yes it's possible to include the bundles in the repo but it's not likely to happen.

**Comment by diegojromerolopez** [comment]
OK. Are there any plans to release a new version with support for Django 1.10 soon?

**Comment by mlavin** [comment]
Sure we can review that since 1.10 is approaching its final release.

**Comment by diegojromerolopez** [comment]
OK, meanwhile I'll fork and fix the project.

Thank you!
